### ISSUE TITLE
Past leaderboard X Rank data is different from the actual final standings

### ISSUE THREAD

**Issue by Sendouc** [misenhower/splatoon3.ink#43]
First of all thanks for making the site I use it all the time and I find the data in json format very useful.

I have a bug report/feature request. I found that past season's leaderboard is different from how it appears in the app. Here is an example:

```json
      "node": {
              "id": "WFJhbmtpbmdIb2xkZXItYToyOmxmOnUtYTM2YXFjYWRjeDc3cm9wYjVubW0=",
              "name": "papoguapo",
              "rank": 336,
              "rankDiff": null,
              "xPower": 2618.7,
              "weapon": {
                "name": "Splash-o-matic",
```
From: https://splatoon3.ink/data/xrank/xrank.detail.a-2.towercontrol.json

![image](https://user-images.githubusercontent.com/38327916/233797405-10f8aa5f-2cfb-4e70-9e21-101cc13c7f0a.png)
From the app (Chill Season 2022 / Tentatek / Tower Control) - screenshot from today.

---

if I had to guess this is that the final "live update" is different from the "final reports" in some cases. Would you consider upgrading the past season data to reflect the final standing? Thanks for consideration.

**Comment by misenhower** [comment]
Hey @Sendouc! Thank you for all your contributions to the Splatoon community as well :) 

You're absolutely right, the data updater missed the last report for the previous season because it was only pulling data for the "current" season.

I just pushed an update to fix this issue. Player papoguapo now correctly shows as rank 342 in the file you linked.

Let me know if you notice any other issues, and thanks for reporting this!!

**Comment by Sendouc** [comment]
Thanks for the quick response! Looks good now :)
